In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df0= pd.read_csv("/content/drive/MyDrive/21-1 대전시 공모전/newsubway.csv", encoding= "cp949")
df2 = pd.read_csv ("/content/drive/Shareddrives/21-1 대전시 공모전/일별.csv")
df3 = pd.read_csv("/content/drive/Shareddrives/21-1 대전시 공모전/일별+역별 승하차 인원/17년_일별.csv",encoding="cp949")
df4 = pd.read_csv("/content/drive/Shareddrives/21-1 대전시 공모전/일별+역별 승하차 인원/18년_일별.csv", encoding="cp949")

In [ ]:
df3_galma= df3[df3['역명']=='갈마']
df4_galma = df4[df4['역명']=='갈마']

In [ ]:
df1 = df0.drop(['school_hu'], axis=1)
df1

        역명   agingindex  bank  bar  ...  ssm  starbucks  theatre  toast
0       갈마   120.354610     2    0  ...    0          0        0      0
1       갑천   132.911150     0    0  ...    1          0        0      0
2       구암   117.880979     1    0  ...    0          0        0      0
3       노은    51.060684     4    3  ...    0          1        1      1
4       대동   118.986175     2    0  ...    0          0        0      0
5       대전  1033.132530     7    0  ...    0          0        0      1
6       반석    51.060684     1    1  ...    0          1        0      1
7      서대전   215.550239     4    3  ...    1          1        1      0
8       시청    70.595037    14    2  ...    1          4        1      1
9       신흥   328.882353     0    2  ...    0          0        0      0
10      오룡   227.010309     3    0  ...    1          0        0      0
11      용문   230.368764     2    2  ...    0          2        1      0
12  월드컵경기장    51.060684     1    0  ...    0          0        0      0
13      월평   132.911150     2    2  ...    1          1        0      0
14    유성온천   117.880979     5    2  ...    0          2        1      0
15    정부청사    70.595037     8    0  ...    1          3        0      1
16     중구청   162.449256     5    0  ...    0          0        0      0
17     중앙로   191.307578     6    1  ...    0          2        1      0
18      지족    51.060684     2    0  ...    1          1        0      0
19      탄방    95.393338     4    2  ...    0          3        1      0
20      판암   328.882353     0    0  ...    0          1        0      0
21     현충원   117.880979     0    0  ...    0          0        0      0

[22 rows x 18 columns]

In [ ]:
df2[0:730]

             날짜  일우량  휴일  장마기간  ...  폭염  평균기온(참조)  최저기온(참조)  최고기온(참조)
0    2017-01-01  0.0   1   0.0  ...   0       3.5      -1.3      10.7
1    2017-01-02  0.0   0   0.0  ...   0       4.7      -0.4      10.8
2    2017-01-03  0.0   0   0.0  ...   0       3.3      -1.5       9.2
3    2017-01-04  0.0   0   0.0  ...   0       4.2      -0.2      10.7
4    2017-01-05  0.0   0   0.0  ...   0       4.3      -0.7       9.3
..          ...  ...  ..   ...  ...  ..       ...       ...       ...
725  2018-12-27  0.0   0   0.0  ...   0      -5.9      -8.4      -1.5
726  2018-12-28  0.0   0   0.0  ...   0      -8.6     -11.1      -4.0
727  2018-12-29  0.0   1   0.0  ...   0      -6.1     -10.7      -0.7
728  2018-12-30  0.0   1   0.0  ...   0      -5.4     -10.4       0.2
729  2018-12-31  0.0   0   0.0  ...   0      -4.7     -10.7       2.5

[730 rows x 10 columns]

In [ ]:
galma = pd.concat([df3_galma , df4_galma])
galma= galma.reset_index().drop(['index'],axis=1)
train_galma = pd.concat([galma, df2[0:730], ],axis=1)

In [ ]:
train_galma

             날짜  역명  이용자 수          날짜  ...  폭염  평균기온(참조)  최저기온(참조)  최고기온(참조)
0    2017-01-01  갈마   3818  2017-01-01  ...   0       3.5      -1.3      10.7
1    2017-01-02  갈마   6367  2017-01-02  ...   0       4.7      -0.4      10.8
2    2017-01-03  갈마   6477  2017-01-03  ...   0       3.3      -1.5       9.2
3    2017-01-04  갈마   6799  2017-01-04  ...   0       4.2      -0.2      10.7
4    2017-01-05  갈마   6827  2017-01-05  ...   0       4.3      -0.7       9.3
..          ...  ..    ...         ...  ...  ..       ...       ...       ...
725  2018-12-27  갈마   6415  2018-12-27  ...   0      -5.9      -8.4      -1.5
726  2018-12-28  갈마   6722  2018-12-28  ...   0      -8.6     -11.1      -4.0
727  2018-12-29  갈마   5136  2018-12-29  ...   0      -6.1     -10.7      -0.7
728  2018-12-30  갈마   4119  2018-12-30  ...   0      -5.4     -10.4       0.2
729  2018-12-31  갈마   6835  2018-12-31  ...   0      -4.7     -10.7       2.5

[730 rows x 13 columns]